config/routes.rb
Rails.application.routes.draw do
  resources :articles do
  	resources :comments, only: [:index, :create]
  end

  resources :comments do
  	resources :comments, only: [:new, :create]
  end

  devise_for :users
  root to: 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable

  delegate :email, to: :user, prefix: :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :comments, class_name: 'Comment', as: :commentable

  belongs_to :commentable, polymorphic: true

  delegate :email, to: :user, prefix: :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

  def my_article? article
  	id == article.user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[edit create update new]
  before_action :user_allowed!, only: %i[edit update]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @comments = @article.comments
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end

    def user_allowed?
      unless current_user.my_article? @article
        redirect_to articles_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def new
		@parent_comment = Comment.find(params[:comment_id])
		@comment = Comment.new
	end

	def create
		if params[:article_id]
			@parent = Article.find(params[:article_id])
		else
			@parent = Comment.find(params[:comment_id])
		end
		@comment = @parent.comments.new(comment_params)
		@comment.user = current_user
		if @comment.valid?
			@comment.save
		end
		# redirect_to @article
	end

	private
	def comment_params
		params.require(:comment).permit(:body)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def my_article? article
		current_user and article.user_id == current_user.id
	end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) if current_user.my_article? article %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } if current_user.my_article? article %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path if user_signed_in? %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_email %>
</p>

<%= link_to 'Edit', edit_article_path(@article) if current_user.my_article? @article%> |
<%= link_to 'Back', articles_path %>

<p>
	<strong>Comments</strong>
	<div><%= render partial: 'comments/new_comment', locals: {parent_object: @article} %></div>
	<div id="comments">
		<%= render partial: 'comments/comment', collection: @comments %>
	</div>
</p>

app/views/comments/_comment.html.erb
<div id="<%= 'comment-' + comment.id.to_s %>">
	<div><%= comment.body %> </div>
	<div>Commented by <%= comment.user_email %></div>
	<%= link_to 'Reply', new_comment_comment_path(comment), remote: true %>
</div>
<br>

app/views/comments/_new_comment.html.erb
<%= form_for [parent_object,@comment], remote: true do |f| %>
  <%= f.label :body %>:
  <%= f.text_field :body %><br />

  <%= f.submit %>
<% end %>

app/views/comments/create.js.erb
document.getElementById('comment_body').value = ''
document.getElementById("comments").innerHTML += "<%= escape_javascript render(partial: 'comment', locals: {comment: @comment})%>"

app/views/comments/new.js.erb
document.getElementById("<%= 'comment-' + @parent_comment.id.to_s %>").innerHTML += "<%= escape_javascript render(partial: 'comments/new_comment', locals: {parent_object: @parent_comment})%>"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>